<?php

namespace App\Tenant\Traits;
use App\Observers\Tenant\TenantObserver;
use App\Scopes\Tenant\TenantScope;
trait TenantTrait
{
    protected static function boot()
    {

        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new TenantScope);
        static::observe(new TenantObserver());
    }
}
