<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Webpatser\Uuid\Uuid;

/**
 * @property integer $id
 * @property string $nome
 * @property string $uuid
 * @property string $nif
 * @property User[] $users
 */
class Tenant extends Model
{
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['nome','uuid','nif'];

    /**
     * @return HasMany
     */
    public function users(): HasMany
    {
        return $this->hasMany('App\Models\User');
    }
    protected static function boot()
    {

        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->uuid = (string) Uuid::generate(4);
        });
    }
}
