const provincias = [

  {
    nome: 'Benguela',
    municipios: [
      'Balombo',
      'Baía',
      'Farta',
      'Benguela',
      'Bocoio',
      'Caimbambo',
      'Catumbela',
      'Chongorói',
      'Cubal',
      'Ganda',
      'Lobito',
    ],
  },
  {
    nome: 'Bie',
    municipios: [
      'Andulo',
      'Camacupa',
      'Catabola',
      'Chinguar',
      'Chitembo',
      'Cuemba',
      'Cunhinga',
      'Cuíto',
      'Nharea',
    ],
  },
  {
    nome: 'Cabinda',
    municipios: [
      'Belize',
      'Buco-Zau',
      'Cabinda',
      'Cacongo',
    ],
  },
  {
    nome: 'Cuando Cubango',
    municipios: [
      'Calai',
      'Cuangar',
      'Cuchi',
      'Cuito Cuanavale',
      'Dirico',
      'Mavinga',
      'Menongue',
      'Nancova',
      'Rivungo',
    ],
  },
  {
    nome: 'Cuanza-Norte',
    municipios: [
      'Ambaca',
      'Banga',
      'Bolongongo',
      'Cambambe',
      'Cazengo',
      'Golungo Alto',
      'Gonguembo',
      'Lucala',
      'Quiculungo',
      'Samba Caju',
    ],
  },
  {
    nome: 'Cuanza-Sul',
    municipios: [
      'Amboim',
      'Cassongue',
      'Cela',
      'Conda',
      'Ebo',
      'Libolo',
      'Mussende',
      'Porto Amboim',
      'Quibala',
      'Quilenda',
      'Seles',
      'Sumbe',
    ],
  },
  {
    nome: 'Cunene',
    municipios: [
      'Cahama',
      'Cuanhama',
      'Curoca',
      'Cuvelai',
      'Namacunde',
      'Ombadja',
    ],
  },
  {
    nome: 'Huambo',
    municipios: [
      'Bailundo',
      'Cachiungo',
      'Caála',
      'Ecunha',
      'Huambo',
      'Londuimbali',
      'Longonjo',
      'Mungo',
      'Chicala-Choloanga',
      'Chinjenje',
      'Ucuma',
    ],
  },
  {
    nome: 'Huila',
    municipios: [
      'Caconda',
      'Cacula',
      'Caluquembe',
      'Chiange',
      'Chibia',
      'Chicomba',
      'Chipindo',
      'Cuvango',
      'Humpata',
      'Jamba',
      'Lubango',
      'Matala',
      'Quilengues',
      'Quipungo',
    ],
  },
  {
    nome: 'Luanda',
    municipios: [
      'Belas',
      'Cacuaco',
      'Cazenga',
      'Ícolo e Bengo',
      'Luanda',
      'Quilamba Quiaxi',
      'Quissama',
      'Talatona',
      'Viana',
    ],
  },
  {
    nome: 'Luanda-Norte',
    municipios: [
      'Cambulo',
      'Capenda-Camulemba',
      'Caungula',
      'Chitato',
      'Cuango',
      'Cuílo',
      'Lóvua',
      'Lubalo',
      'Lucapa',
      'Xá-Muteba',
    ],
  },
  {
    nome: 'Luanda-Sul',
    municipios: [
      'Cacolo',
      'Dala',
      'Muconda',
      'Saurimo',
    ],
  },
  {
    nome: 'Malange',
    municipios: [
      'Cacuso',
      'Calandula',
      'Cambundi-Catembo',
      'Cangandala',
      'Caombo',
      'Cuaba Nzoji',
      'Cunda-Dia-Baze',
      'Luquembo',
      'Malanje',
      'Marimba',
      'Massango',
      'Mucari',
      'Quela',
      'Quirima',
    ],
  },
  {
    nome: 'Moxico',
    municipios: [
      'Alto Zambeze',
      'Bundas',
      'Camanongue',
      'Léua',
      'Luau',
      'Luacano',
      'Luchazes',
      'Cameia',
      'Moxico',
    ],
  },
  {
    nome: 'Namibe',
    municipios: [
      'Bibala',
      'Camucuio',
      'Moçâmedes',
      'Tômbua',
      'Virei',
    ],
  },
  {
    nome: 'Uige',
    municipios: [
      'Alto Cauale',
      'Ambuíla',
      'Bembe',
      'Buengas',
      'Bungo',
      'Damba',
      'Milunga',
      'Mucaba',
      'Negage',
      'Puri',
      'Quimbele',
      'Quitexe',
      'Sanza Pombo',
      'Songo',
      'Uíge',
      'Zombo',
    ],
  },
  {
    nome: 'Zaire',
    municipios: [
      'Cuimba',
      'Mabanza Congo',
      'Nóqui',
      'Nezeto',
      'Soio',
      'Tomboco',
    ],
  },
];
export default provincias;
